repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-ast
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: trailing-whitespace
    - id: pretty-format-json
      args:
        - --autofix
- repo: https://github.com/hhatto/autopep8
  rev: v2.3.1
  hooks:
    - id: autopep8
      args:
        - --in-place
        - --max-line-length=99
# We run pylint from local env, to ensure modules can be found
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: python3 -m pylint.__main__
      language: system
      types: [python]
      args:
        - --include-naming-hint=yes
        - --max-args=10
        - --max-returns=10
        - --ignore-imports=yes
        - --disable=arguments-differ
        - --disable=attribute-defined-outside-init
        - --disable=broad-except
        - --disable=broad-exception-raised
        - --disable=c-extension-no-member
        - --disable=consider-using-f-string
        - --disable=deprecated-module
        - --disable=duplicate-code
        - --disable=missing-docstring
        - --disable=protected-access
        - --disable=raise-missing-from
        - --disable=too-few-public-methods
        - --disable=too-many-instance-attributes
        - --disable=too-many-lines
        - --disable=too-many-locals
        - --disable=too-many-positional-arguments
        - --disable=too-many-public-methods
        - --disable=try-except-raise
        - --disable=use-a-generator
        - --disable=useless-return
