repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: autopep8-wrapper
      args:
        - --in-place
        - --max-line-length=99
    - id: flake8
      args:
        - --max-line-length=99
    - id: check-ast
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: trailing-whitespace
    - id: pretty-format-json
      args:
        - --autofix
# We run pylint from local env, to ensure modules can be found
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: python -m pylint.__main__
      language: system
      types: [python]
      args:
        - --include-naming-hint=yes
        - --max-args=7
        - --disable=attribute-defined-outside-init
        - --disable=missing-docstring
        - --disable=too-many-instance-attributes
