version: '3'
services:

  activity-stream:
    depends_on:
      - activity-stream-redis
      - opensearch
      - verification-feed
    build:
      context: .
    restart: always
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - 'VCAP_SERVICES={"redis":[{"credentials":{"uri":"redis://activity-stream-redis:6379"}}],"opensearch":[{"credentials":{"uri":"http://some-id:some-secret@opensearch:9200"}, "plan": "123-123-123" } ] }'
      - SENTRY_ENVIRONMENT=test
      - SENTRY_DSN=http://abc:cvb@localhost:9872/123
      - FEEDS__1__UNIQUE_ID=verification_feed_app
      - FEEDS__1__SEED=http://verification-feed:8100/0
      - FEEDS__1__ACCESS_KEY_ID=some-id
      - FEEDS__1__SECRET_ACCESS_KEY=some-secret
      - FEEDS__1__TYPE=activity_stream
      - INCOMING_ACCESS_KEY_PAIRS__1__KEY_ID=incoming-some-id-1
      - INCOMING_ACCESS_KEY_PAIRS__1__SECRET_KEY=incoming-some-secret-1
      - INCOMING_ACCESS_KEY_PAIRS__1__PERMISSIONS__activities__1=__MATCH_ALL__
      - INCOMING_ACCESS_KEY_PAIRS__1__PERMISSIONS__objects__1=__MATCH_ALL__
      - INCOMING_IP_WHITELIST__1=1.2.3.4
      - INCOMING_IP_WHITELIST__2=2.3.4.5
      - PYTHONUNBUFFERED=1

  verification-feed:
    depends_on:
      - activity-stream-redis
      - opensearch
    build:
      context: ./verification_feed
    restart: always
    ports:
      - 8100:8100
    environment:
      - PORT=8100

  activity-stream-redis:
    image: redis:6.2.6
    restart: always
    ports:
      - '6379:6379'

  opensearch:
    image: opensearchproject/opensearch:1.2.4
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - cluster.name=cluster-001
      - node.name=node-001
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - DISABLE_INSTALL_DEMO_CONFIG=true # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - DISABLE_SECURITY_PLUGIN=true # Disables security plugin
