import asyncio
import datetime
import re
import aiohttp
import yarl

from .hawk import (
    get_hawk_header,
)
from .http import (
    http_make_request,
)
from .logger import (
    logged,
)
from .utils import (
    json_loads,
    sub_dict_lower,
)
from . import settings


def parse_feed_config(feed_config):
    by_feed_type = {
        'activity_stream': ActivityStreamFeed,
        'zendesk': ZendeskFeed,
        'aventri': EventFeed,
    }
    return by_feed_type[feed_config['TYPE']].parse_config(feed_config)


class ActivityStreamFeed:

    down_grace_period = 60 * 2

    full_ingest_page_interval = 0.25
    updates_page_interval = 1
    exception_intervals = [1, 2, 4, 8, 16, 32, 64]

    @classmethod
    def parse_config(cls, config):
        return cls(**sub_dict_lower(config,
                                    ['UNIQUE_ID', 'SEED', 'ACCESS_KEY_ID', 'SECRET_ACCESS_KEY']))

    def __init__(self, unique_id, seed, access_key_id, secret_access_key):
        self.lock = asyncio.Lock()
        self.unique_id = unique_id
        self.seed = seed
        self.access_key_id = access_key_id
        self.secret_access_key = secret_access_key

    @staticmethod
    def next_href(feed):
        return feed.get('next', None)

    async def auth_headers(self, _, url):
        parsed_url = yarl.URL(url)
        return {
            'Authorization': get_hawk_header(
                access_key_id=self.access_key_id,
                secret_access_key=self.secret_access_key,
                method='GET',
                host=parsed_url.host,
                port=str(parsed_url.port),
                path=parsed_url.raw_path_qs,
                content_type=b'',
                content=b'',
            )
        }

    @classmethod
    async def get_activities(cls, _, feed):
        return feed['orderedItems']


class ZendeskFeed:

    down_grace_period = 400

    # The staging API is severely rate limited
    # Could be higher on prod, but KISS
    full_ingest_page_interval = 30
    updates_page_interval = 120
    exception_intervals = [120, 180, 240, 300]

    company_number_regex = r'Company number:\s*(\d+)'

    @classmethod
    def parse_config(cls, config):
        return cls(**sub_dict_lower(config, ['UNIQUE_ID', 'SEED', 'API_EMAIL', 'API_KEY']))

    def __init__(self, unique_id, seed, api_email, api_key):
        self.lock = asyncio.Lock()
        self.unique_id = unique_id
        self.seed = seed
        self.api_email = api_email
        self.api_key = api_key

    @staticmethod
    def next_href(feed):
        return feed['next_page']

    async def auth_headers(self, _, __):
        return {
            'Authorization': aiohttp.helpers.BasicAuth(
                login=self.api_email + '/token',
                password=self.api_key,
            ).encode()
        }

    @classmethod
    async def get_activities(cls, _, page):
        def company_numbers(description):
            match = re.search(cls.company_number_regex, description)
            return [match[1]] if match else []

        return [
            {
                'id': 'dit:zendesk:Ticket:' + str(ticket['id']) + ':Create',
                'type': 'Create',
                'published': ticket['created_at'],
                'dit:application': 'zendesk',
                'actor': {
                    'type': [
                        'Organization',
                        'dit:company',
                    ],
                    'dit:companiesHouseNumber': company_number,
                },
                'object': {
                    'type': [
                        'Document',
                        'dit:zendesk:Ticket',
                    ],
                    'id': 'dit:zendesk:Ticket:' + str(ticket['id']),
                },
            }
            for ticket in page['tickets']
            for company_number in company_numbers(ticket['description'])
        ]


class EventFeed:

    down_grace_period = 60 * 60 * 4

    full_ingest_page_interval = 3
    updates_page_interval = 60 * 60 * 24 * 30
    exception_intervals = [120, 180, 240, 300]

    @classmethod
    def parse_config(cls, config):
        return cls(**sub_dict_lower(
            config, ['UNIQUE_ID', 'SEED', 'ACCOUNT_ID', 'API_KEY', 'AUTH_URL', 'EVENT_URL',
                     'WHITELISTED_FOLDERS']))

    def __init__(self, unique_id, seed, account_id, api_key,
                 auth_url, event_url, whitelisted_folders):
        self.lock = asyncio.Lock()
        self.unique_id = unique_id
        self.seed = seed
        self.account_id = account_id
        self.api_key = api_key
        self.auth_url = auth_url
        self.event_url = event_url
        self.accesstoken = None
        self.whitelisted_folders = whitelisted_folders

    @staticmethod
    def next_href(_):
        """ aventri API does not support pagination
            returns (None)
        """
        return None

    async def auth_headers(self, context, __):
        result = await http_make_request(
            context.session, context.metrics, 'POST', self.auth_url, data={
                'accountid': self.account_id, 'key': self.api_key,
            }, headers={})
        result.raise_for_status()

        self.accesstoken = json_loads(result._body)['accesstoken']
        return {
            'accesstoken': self.accesstoken,
        }

    async def get_activities(self, context, page):
        async def get_event(event_id):
            await asyncio.sleep(3)
            url = self.event_url.format(event_id=event_id)

            with logged(context.logger.debug, context.logger.warning,
                        'Fetching event (%s)', [url]):
                result = await http_make_request(
                    context.session, context.metrics, 'GET', url, data=b'',
                    headers={'accesstoken': self.accesstoken})
                result.raise_for_status()

            event = json_loads(result._body)

            if ('location' in event.keys()) and ('postcode' in event['location'].keys()):
                postcode = event['location']['postcode']

                # Search Reddis first
                redis_lookup = await context.redis_client.execute('GET', f'address-{postcode}')
                if redis_lookup:
                    split_lat_lng = redis_lookup.decode('ascii').split(',')
                    event['geocoordinates']['latitude'] = split_lat_lng[0]
                    event['geocoordinates']['longitude'] = split_lat_lng[1]
                else:  # Try AddressLookup API
                    async with aiohttp.ClientSession() as session:
                        api_key = settings.GETADDRESS_API_KEY
                        async with session.get(
                                f'https://api.getaddress.io/find/{postcode}?api-key={api_key}'
                        ) as resp:
                            resp_body = await resp.text()
                            geo_result = json_loads(resp_body)
                            if 'latitude' in geo_result.keys():
                                event['geocoordinates']['lat'] = str(geo_result['latitude'])
                                event['geocoordinates']['lon'] = str(geo_result['longitude'])
                                joined_lat_lng = ','.join(
                                    [str(geo_result['latitude']), str(geo_result['longitude'])])
                                await context.redis_client.execute(
                                    'SET', 'address-{postcode}', joined_lat_lng)

            return event

        return [
            {'id': 'dit:aventri:Event:200190654:Create', 'type': 'Search', 'eventid': '200190654', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '49.06', 'lon': '6.54' }, 'id': 'dit:aventri:Event:200190654', 'name': 'Registration of Interest: Midlands Engine Market Visit to CONEXPO-CON/AGG 2020 ', 'url': 'https://eu.eventscloud.com/200190654', 'content': '<p>Join our visit to CONEXPO-CON/AGG 2020, North America’s largest construction exhibition. This event is organised by the East Midlands.</p>', 'startdate': '2020-03-10', 'enddate': '2020-03-14', 'foldername': 'East Midlands', 'location': {'name': 'Las Vegas, USA ', 'address1': 'Convention Center & Festival Grounds', 'address2': '', 'address3': '', 'city': '', 'state': '', 'postcode': '', 'country': 'United States', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200195340:Create', 'type': 'Search', 'eventid': '200195340', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '09.53', 'lon': '3.40' }, 'id': 'dit:aventri:Event:200195340', 'name': ' Sharing UK Expertise in Oncology ', 'url': 'https://eu.eventscloud.com/200195340', 'content': '', 'startdate': '2020-03-11', 'enddate': '2020-03-11', 'foldername': 'DIT HQ events and sites', 'location': {'name': '', 'address1': '', 'address2': '', 'address3': '', 'city': '', 'state': '', 'postcode': '', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200195776:Create', 'type': 'Search', 'eventid': '200195776', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '69.57', 'lon': '7.76' }, 'id': 'dit:aventri:Event:200195776', 'name': 'Global Aid and Development Directory ', 'url': 'https://eu.eventscloud.com/200195776', 'content': 'DIT is producing a directory of companies who supply, or would like to supply, relevant humanitarian aid and development products and services to the United Nations family of organisations and NGOs.  ', 'startdate': '2020-03-10', 'enddate': '2020-03-12', 'foldername': '1920 Events', 'location': {'name': '', 'address1': '', 'address2': '', 'address3': '', 'city': '', 'state': '', 'postcode': '', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200196713:Create', 'type': 'Search', 'eventid': '200196713', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '39.67', 'lon': '7.13' }, 'id': 'dit:aventri:Event:200196713', 'name': 'SxSW 2020', 'url': 'https://eu.eventscloud.com/200196713', 'content': '<h2><em>Are you attending SxSW 2020? </em></h2>\r\n\r\n<p>Whether you’re looking to return to SxSW or you’re a company interested in attending for the first time, we want you to join the UK Department for International Trade (DIT) at SxSW to get the most from this celebration of the convergence of the interactive, film, and music industries in\xa0March 2020 in\xa0Austin, USA.</p>\r\n\r\n<p>SxSW is a world class destination for discovery and offers endless opportunities to foster business development and professional growth alike. The 10-day festival has an estimated 300,000 visitors. From entrepreneurs and investors to cutting-edge digital disruptors – the perfect audience for you to make contacts and demonstrate your company’s creativity, expertise, technology and innovation offering.</p>', 'startdate': '2020-03-13', 'enddate': '2020-03-22', 'foldername': '1920 Events', 'location': {'name': 'South by Southwest is held at various venues throughout Austin, Texas', 'address1': '', 'address2': '', 'address3': '', 'city': 'Austin', 'state': 'Texas', 'postcode': '', 'country': 'United States', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[UTC] Coordinated Universal Time', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200196717:Create', 'type': 'Search', 'eventid': '200196717', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '79.67', 'lon': '7.17' }, 'id': 'dit:aventri:Event:200196717', 'name': 'Exporting: Is it for you?', 'url': 'https://eu.eventscloud.com/200196717', 'content': '<p>This free morning workshop will help you to decide whether or not exporting is right for your business, and showcase the breadth of support available to all.</p>', 'startdate': '2020-03-18', 'enddate': '2020-03-18', 'foldername': 'East Midlands', 'location': {'name': 'Sharpe’s Pottery Museum', 'address1': '23 West Street', 'address2': '', 'address3': '', 'city': 'Swadlincote', 'state': 'Derbyshire', 'postcode': 'DE11 9DG', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200197663:Create', 'type': 'Search', 'eventid': '200197663', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '39.76', 'lon': '6.63' }, 'id': 'dit:aventri:Event:200197663', 'name': 'India China LSHC Roadshow 2020', 'url': 'https://eu.eventscloud.com/200197663', 'content': 'India China Life Sciences & Healthcare Roadshow 2020', 'startdate': '2020-03-16', 'enddate': '2020-03-20', 'foldername': 'Healthcare and Life Science', 'location': {'name': 'Various cities across UK (select the event you would like to attend during registration)', 'address1': '', 'address2': '', 'address3': '', 'city': 'Newcastle, Loughbrough, London, Oxford, Belfast', 'state': '', 'postcode': '', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200197961:Create', 'type': 'Search', 'eventid': '200197961', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '19.79', 'lon': '9.61' }, 'id': 'dit:aventri:Event:200197961', 'name': 'Higher Education Mission to  Saudi Arabia', 'url': 'https://eu.eventscloud.com/200197961', 'content': 'DIT higher education trade mission to Saudi Arabia to explore opportunities for partnerships in transnational education, research and student recruitment.', 'startdate': '2020-04-04', 'enddate': '2020-04-08', 'foldername': 'Education', 'location': {'name': 'Saudi Arabia', 'address1': '', 'address2': '', 'address3': '', 'city': 'Riyadh', 'state': '', 'postcode': '', 'country': 'Saudi Arabia', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200198183:Create', 'type': 'Search', 'eventid': '200198183', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '39.81', 'lon': '1.83' }, 'id': 'dit:aventri:Event:200198183', 'name': 'YOU CAN EXPORT: Introduction to International Trade ', 'url': 'https://eu.eventscloud.com/200198183', 'content': '<p style="margin:0cm 0cm 0pt">\xa0</p>\r\n\r\n<p style="margin:0cm 0cm 0pt"><strong>Please note this is a practical event aimed at North East based businesses interested in trading internationally or wanting to learn more about the service Department for International Trade North East (formerly UKTI North East) provides.\xa0</strong></p>', 'startdate': '2020-03-18', 'enddate': '2020-03-18', 'foldername': 'Northeast', 'location': {'name': 'Durham County Cricket Club ', 'address1': '', 'address2': 'Emirates Riverside', 'address3': 'Chester-le-Street', 'city': 'Durham', 'state': '', 'postcode': 'DH3 3QR', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200198227:Create', 'type': 'Search', 'eventid': '200198227', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '79.82', 'lon': '2.27' }, 'id': 'dit:aventri:Event:200198227', 'name': 'Olympic & Paralympic Games: Embracing the Sustainability Challenge', 'url': 'https://eu.eventscloud.com/200198227', 'content': 'A morning conference dedicated to the organisation of sustainable Olympic and Paralympic Games.', 'startdate': '2020-03-05', 'enddate': '2020-03-05', 'foldername': 'France', 'location': {'name': '', 'address1': '', 'address2': '', 'address3': '', 'city': 'Paris', 'state': '', 'postcode': '', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT+01:00] Brussels, Copenhagen, Madrid, Paris', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200198344:Create', 'type': 'Search', 'eventid': '200198344', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '49.83', 'lon': '3.44' }, 'id': 'dit:aventri:Event:200198344', 'name': 'Independent Hotel Show', 'url': 'https://eu.eventscloud.com/200198344', 'content': 'The Independent Hotel Show is the only industry event dedicated entirely to the needs of luxury and boutique hoteliers. It was founded in London in 2012 to support, share, educate and inspire the hotelier community.\r\nIn order to address demand from the growing European market the event was expanded, and the first European Independent Hotel Show was held in Amsterdam in May 2019. Serving an audience of 2,300 independently spirited hoteliers, the show brought its experience and passion to build and support the hotelier communities across Europe. \r\nThe Department for International Trade (DIT) in association with our partners the British Contract Furniture Association (BCFA) will host a UK Pavilion at the Independent Hotel Show, Amsterdam promoting the wealth of UK design, innovation and creativity within the UK’s interior design sector. The Pavilion will bring together experienced UK companies to showcase their expertise and services at this key international event. \r\nExhibiting at the Independent Hotel Show provides the perfect opportunity to promote your company to an audience of over 6300 owners and operators from European luxury, boutique and independent hotels.', 'startdate': '2020-03-17', 'enddate': '2020-03-18', 'foldername': '1920 Events', 'location': {'name': 'RAI Amsterdam', 'address1': 'Europaplein 22', 'address2': '', 'address3': '', 'city': 'Amsterdam', 'state': '', 'postcode': '1078 GZ', 'country': 'Netherlands', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200198360:Create', 'type': 'Search', 'eventid': '200198360', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '09.83', 'lon': '3.60' }, 'id': 'dit:aventri:Event:200198360', 'name': 'BETT Asia 2020', 'url': 'https://eu.eventscloud.com/200198360', 'content': 'Industry Exhibition focusing on education technology & schools equipment including a summit/dialogue in the margins.  This is a major regional hub event which guarantees senior level attendance from around South East Asia.  Education Team are keen to take the opportunity to expand our presence to a wider strategic role, so perhaps Ministerial meetings in the margins to discussion Market Access.', 'startdate': '2020-06-23', 'enddate': '2020-06-24', 'foldername': '1920 Events', 'location': {'name': '', 'address1': '', 'address2': '', 'address3': '', 'city': 'Kuala Lumpa', 'state': '', 'postcode': '', 'country': 'Malaysia', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200198628:Create', 'type': 'Search', 'eventid': '200198628', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '89.86', 'lon': '6.28' }, 'id': 'dit:aventri:Event:200198628', 'name': 'You Can Export: Working with Overseas Agents, Distributors and Other Partners', 'url': 'https://eu.eventscloud.com/200198628', 'content': "Your international contacts are a vital part of selling overseas. In this half-day workshop, we'll look at how to identify useful contacts overseas, as well as how to source your ideal agent or distributor and evaluate their performance to improve your chances of international success.", 'startdate': '2020-03-05', 'enddate': '2020-03-05', 'foldername': 'Yorkshire & Humber', 'location': {'name': 'Mercure Sheffield Parkway Hotel', 'address1': 'Britannia Way', 'address2': 'Catcliffe', 'address3': '', 'city': 'Sheffield', 'state': '', 'postcode': 'S60 5BD', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200198669:Create', 'type': 'Search', 'eventid': '200198669', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '99.86', 'lon': '6.69' }, 'id': 'dit:aventri:Event:200198669', 'name': 'Saudi ELT Expo and Conference', 'url': 'https://eu.eventscloud.com/200198669', 'content': 'English Language Training Coneference', 'startdate': '2021-01-28', 'enddate': '2021-01-30', 'foldername': 'Education', 'location': {'name': 'King Abdulaziz University', 'address1': '', 'address2': '', 'address3': '', 'city': 'Jeddah', 'state': '', 'postcode': '', 'country': 'Saudi Arabia', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[UTC] Coordinated Universal Time', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200198738:Create', 'type': 'Search', 'eventid': '200198738', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '89.87', 'lon': '7.38' }, 'id': 'dit:aventri:Event:200198738', 'name': 'You Can Export: Pitching for Business Overseas', 'url': 'https://eu.eventscloud.com/200198738', 'content': "When face-to-face with prospective customers, you'll need to persuade them why they should be buying from you rather than your competitors. In this session, participants will gain an insight into some of the elements that make successful salespeople successful.", 'startdate': '2020-03-19', 'enddate': '2020-03-19', 'foldername': 'Yorkshire & Humber', 'location': {'name': 'Advanced Manufacturing Park', 'address1': 'Brunel Way', 'address2': '', 'address3': '', 'city': 'Rotherham', 'state': 'County', 'postcode': 'S60 5WG', 'country': 'Country', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200198821:Create', 'type': 'Search', 'eventid': '200198821', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '19.88', 'lon': '8.21' }, 'id': 'dit:aventri:Event:200198821', 'name': 'You Can Export: Business Culture in China', 'url': 'https://eu.eventscloud.com/200198821', 'content': 'This half-day workshop brought to you by the Department for International Trade is designed to develop your confidence in working with the Chinese. It will focus primarily on the practical elements of working in China and how to communicate and work effectively with the Chinese.', 'startdate': '2020-03-18', 'enddate': '2020-03-18', 'foldername': 'Yorkshire & Humber', 'location': {'name': 'Yorkshire Sculpture Park', 'address1': 'West Bretton', 'address2': '', 'address3': '', 'city': 'Wakefield', 'state': 'West Yorkshire', 'postcode': 'WF4 4LG', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200198899:Create', 'type': 'Search', 'eventid': '200198899', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '99.88', 'lon': '8.99' }, 'id': 'dit:aventri:Event:200198899', 'name': 'Latin America and the Caribbean UK Roadshow 2020', 'url': 'https://eu.eventscloud.com/200198899', 'content': '', 'startdate': '2020-03-09', 'enddate': '2020-03-13', 'foldername': '1920 Events', 'location': {'name': '', 'address1': '', 'address2': '', 'address3': '', 'city': '', 'state': '', 'postcode': '', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200198902:Create', 'type': 'Search', 'eventid': '200198902', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '29.89', 'lon': '9.02' }, 'id': 'dit:aventri:Event:200198902', 'name': 'You Can Export: Preparing Your Business for International Travel', 'url': 'https://eu.eventscloud.com/200198902', 'content': "Get your company ready for international business travel in this half-day workshop. From planning your journey to keeping your employees safe, we'll give you practical advice and tips to ensure you make the most out of every trip.", 'startdate': '2020-03-10', 'enddate': '2020-03-10', 'foldername': 'Yorkshire & Humber', 'location': {'name': 'Hallmark Hotel', 'address1': 'Ferriby High Road', 'address2': '', 'address3': '', 'city': 'North Ferriby', 'state': 'County', 'postcode': 'HU14 3LG', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200198955:Create', 'type': 'Search', 'eventid': '200198955', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '59.89', 'lon': '9.55' }, 'id': 'dit:aventri:Event:200198955', 'name': 'You Can: Export Fashion Overseas', 'url': 'https://eu.eventscloud.com/200198955', 'content': 'Smaller UK fashion companies have much to gain from selling their products overseas. A global demand for UK products, coupled with increasing e-commerce and exhibition opportunities, has helped the UK fashion sector generate billions of pounds each year. \r\n\r\nThe Department for International Trade in the East of England has joined with the UK Fashion & Textile Association (UKFT) to bring you a workshop exploring how your company can sell its products to international markets.', 'startdate': '2020-04-01', 'enddate': '2020-04-01', 'foldername': 'East of England', 'location': {'name': 'Lanwades Hall', 'address1': 'Kentford', 'address2': '', 'address3': '', 'city': 'Newmarket', 'state': 'Suffolk', 'postcode': 'CB8 7UA', 'country': 'United Kingdom', 'phone': '01707 398 398', 'email': 'diteastevents@mobile.trade.gov.uk', 'map': 'https://www.lanwadeshall.co.uk/contact-us/'}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200199009:Create', 'type': 'Search', 'eventid': '200199009', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '99.90', 'lon': '0.09' }, 'id': 'dit:aventri:Event:200199009', 'name': 'DIT Sports Economy Conference 2020', 'url': 'https://eu.eventscloud.com/200199009', 'content': '<p>We are very pleased to announce the return of the DIT Sports Economy Conference which will take place this year in London on Tuesday 24th March.\xa0</p>\r\n\r\n<p><br />\r\nThis unique event brings together UK companies from across the dynamic sports sector and will provide a fantastic opportunity to connect, learn and build relationships.\xa0</p>\r\n\r\n<p><br />\r\nThis one-day event will follow an exciting programme with discussions on the power and influence of major sports events, as well as the opportunities within emerging markets, evolving trends, and growing sports economies around the globe.\xa0</p>\r\n\r\n<p><br />\r\nThe Conference will provide the opportunity to learn about the UK Government’s work to support exporters and investors both overseas and in the UK.\xa0</p>', 'startdate': '2020-03-24', 'enddate': '2020-03-24', 'foldername': '1920 Events', 'location': {'name': 'Stamford Bridge Stadium', 'address1': 'Fulham Road', 'address2': 'Fulham', 'address3': '', 'city': 'London', 'state': '', 'postcode': 'SW6 1HS', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200199077:Create', 'type': 'Search', 'eventid': '200199077', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '79.90', 'lon': '0.77' }, 'id': 'dit:aventri:Event:200199077', 'name': 'Chinese Financial Market Infrastructure 2020', 'url': 'https://eu.eventscloud.com/200199077', 'content': 'The Department for International Trade (DIT) in China is organising a UK FinTech Financial Market Infrastructure (FMIs) Trade mission to China to attend a week’s events and activities during the week of 18th March. This trade mission offers UK FinTech firms a unique opportunity to meet key Chinese stakeholders including government and regulatory officials, financial services businesses, investors and industry experts to facilitate communication and explore cooperation opportunities in the Chinese market. ', 'startdate': '2020-03-18', 'enddate': '2020-03-24', 'foldername': 'China', 'location': {'name': '', 'address1': '', 'address2': '', 'address3': '', 'city': 'Shenzhen, Shanghai and Beijing', 'state': '', 'postcode': '', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200199119:Create', 'type': 'Search', 'eventid': '200199119', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '99.91', 'lon': '1.19' }, 'id': 'dit:aventri:Event:200199119', 'name': 'MIPIM 2020', 'url': 'https://eu.eventscloud.com/200199119', 'content': 'MIPIM, the premier real estate event, gathers the most influential players from all sectors of the international property industry for four days of networking, learning and transaction through premium events, conferences and dedicated exhibition zones.', 'startdate': '2020-03-10', 'enddate': '2020-03-13', 'foldername': '1920 Events', 'location': {'name': 'Palais des Festivals', 'address1': '', 'address2': '', 'address3': '', 'city': 'Cannes, France', 'state': '', 'postcode': '', 'country': 'France', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200199189:Create', 'type': 'Search', 'eventid': '200199189', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '99.91', 'lon': '1.89' }, 'id': 'dit:aventri:Event:200199189', 'name': 'Global Resilience Summit 2020', 'url': 'https://eu.eventscloud.com/200199189', 'content': 'The Government of the United Kingdon Department for International Trade will convene the Global Resilience Summit. The Global Resilience Summit will be a 4-day event, bringing together a wide range of stakeholders from across government and industry with responsibility for resilience and providers of resilience finance and services.', 'startdate': '2020-06-16', 'enddate': '2020-06-19', 'foldername': '1920 Events', 'location': {'name': 'London', 'address1': ' ', 'address2': '', 'address3': '', 'city': '', 'state': '', 'postcode': '', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200199429:Create', 'type': 'Search', 'eventid': '200199429', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '99.94', 'lon': '4.29' }, 'id': 'dit:aventri:Event:200199429', 'name': 'Digital Trade Advice Clinic: March 2020', 'url': 'https://eu.eventscloud.com/200199429', 'content': '<p>Receive 1 hour of tailored advice on the best strategies available for growing globally online.</p>', 'startdate': '2020-03-18', 'enddate': '2020-03-18', 'foldername': 'East Midlands', 'location': {'name': 'The International Trade Centre', 'address1': '5 Merus Court', 'address2': 'Meridian Business Park', 'address3': '', 'city': 'Leicester', 'state': '', 'postcode': 'LE19 1RP', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200199746:Create', 'type': 'Search', 'eventid': '200199746', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '69.97', 'lon': '7.46' }, 'id': 'dit:aventri:Event:200199746', 'name': 'You Can Export: Researching and Selecting Overseas Markets', 'url': 'https://eu.eventscloud.com/200199746', 'content': 'Whether you wish to concentrate on new and emerging markets or advanced economies, this workshop will provide you with skills and techniques to enable you to select and prioritise potential export markets with confidence.', 'startdate': '2020-03-24', 'enddate': '2020-03-24', 'foldername': 'Yorkshire & Humber', 'location': {'name': 'The Source Skills Academy', 'address1': '300 Meadowhall Way', 'address2': '', 'address3': '', 'city': 'Sheffield', 'state': '', 'postcode': 'S9 1EA', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200199747:Create', 'type': 'Search', 'eventid': '200199747', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '79.97', 'lon': '7.47' }, 'id': 'dit:aventri:Event:200199747', 'name': 'AGEING SOCIETY: CAPITALISING ON OPPORTUNITIES IN DIGITAL HEALTH', 'url': 'https://eu.eventscloud.com/200199747', 'content': '', 'startdate': '2020-03-10', 'enddate': '2020-03-10', 'foldername': 'France', 'location': {'name': 'HMA Residence', 'address1': '39 Rue du Faubourg Saint Honoré', 'address2': '', 'address3': '', 'city': 'Paris', 'state': '', 'postcode': '', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT+01:00] Brussels, Copenhagen, Madrid, Paris', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200199804:Create', 'type': 'Search', 'eventid': '200199804', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '49.98', 'lon': '8.04' }, 'id': 'dit:aventri:Event:200199804', 'name': 'You Can Export: Export Pricing', 'url': 'https://eu.eventscloud.com/200199804', 'content': 'This masterclass will assist delegates in recognising all the cost factors (including the hidden costs) involved in marketing and delivering their products and services to overseas customers.', 'startdate': '2020-03-09', 'enddate': '2020-03-09', 'foldername': 'Northwest', 'location': {'name': 'Square Kilometre Array, Jodrell Bank', 'address1': 'Lower Withington', 'address2': '', 'address3': '', 'city': 'Macclesfield', 'state': 'Cheshire', 'postcode': 'SK11 9FT', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200199806:Create', 'type': 'Search', 'eventid': '200199806', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '69.98', 'lon': '8.06' }, 'id': 'dit:aventri:Event:200199806', 'name': 'You Can Export: How to Manage Agents and Distributors', 'url': 'https://eu.eventscloud.com/200199806', 'content': 'The use of agents and distributors to enter international markets is common. But is it the best method for North West businesses? And if it is, how can you build and manage a network of these trade multipliers?', 'startdate': '2020-03-19', 'enddate': '2020-03-19', 'foldername': 'Northwest', 'location': {'name': 'Village Hotel Club', 'address1': '110 Centre Park Square', 'address2': '', 'address3': '', 'city': 'Warrington', 'state': '', 'postcode': 'WA1 1QA', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200199821:Create', 'type': 'Search', 'eventid': '200199821', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '19.98', 'lon': '8.21' }, 'id': 'dit:aventri:Event:200199821', 'name': 'Become a Winning Negotiator', 'url': 'https://eu.eventscloud.com/200199821', 'content': 'Negotiations occur daily at all levels of business. From discussions with colleagues to closing an important deal, the ability to negotiate is integral across a wide spectrum of activities. Effective sales negotiations can make a significant difference to export performance.  When selling internationally, negotiation is a crucial skill to creating beneficial relationships with clients, partners, agents and distributors. ', 'startdate': '2020-03-24', 'enddate': '2020-03-24', 'foldername': 'East of England', 'location': {'name': 'Anglia Ruskin University Chelmsford Campus', 'address1': 'Lord Ashcroft Building', 'address2': 'Bishop Hall Lane', 'address3': '', 'city': 'Chelmsford', 'state': 'Essex', 'postcode': 'CM1 1SQ', 'country': 'United Kingdom', 'phone': '01707 398 398', 'email': 'diteastevents@mobile.trade.gov.uk', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200199890:Create', 'type': 'Search', 'eventid': '200199890', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '09.98', 'lon': '8.90' }, 'id': 'dit:aventri:Event:200199890', 'name': '2020 Smart Cities Mission to Brazil', 'url': 'https://eu.eventscloud.com/200199890', 'content': '', 'startdate': '2020-03-23', 'enddate': '2020-03-27', 'foldername': 'Brazil', 'location': {'name': '', 'address1': '', 'address2': '', 'address3': '', 'city': 'São Paulo', 'state': '', 'postcode': '', 'country': 'Brazil', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT-03:00] Brasilia', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200200514:Create', 'type': 'Search', 'eventid': '200200514', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '40.05', 'lon': '5.14' }, 'id': 'dit:aventri:Event:200200514', 'name': 'You Can Export: Selling Internationally for Service Providers', 'url': 'https://eu.eventscloud.com/200200514', 'content': 'This workshop will aim to address the processes involved and concerns of service companies seeking to enter international markets for the first time and build an international brand.', 'startdate': '2020-03-24', 'enddate': '2020-03-24', 'foldername': 'Northwest', 'location': {'name': 'Workplace', 'address1': 'Fourth Floor, Churchgate House', 'address2': '56 Oxford Street', 'address3': '', 'city': 'Manchester', 'state': 'Greater Manchester', 'postcode': 'M1 6EU', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200200631:Create', 'type': 'Search', 'eventid': '200200631', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '10.06', 'lon': '6.31' }, 'id': 'dit:aventri:Event:200200631', 'name': 'Meet the Expert: Opportunities in the Eastern Economic Corridor, Thailand', 'url': 'https://eu.eventscloud.com/200200631', 'content': 'Thailand presents many exciting opportunities for businesses, particularly along the vast Eastern Economic Corridor (EEC) project. To find out more about this government-funded project, and how your business can get involved, join DIT as we welcome Graham Macdonald, former British Chamber of Commerce Thailand Chairman, to Huddersfield.', 'startdate': '2020-03-23', 'enddate': '2020-03-23', 'foldername': 'Yorkshire & Humber', 'location': {'name': '3M Buckley Innovation Centre', 'address1': 'Firth Street', 'address2': '', 'address3': '', 'city': 'Huddersfield', 'state': 'West Yorkshire', 'postcode': 'HD1 3BD', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200200648:Create', 'type': 'Search', 'eventid': '200200648', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '80.06', 'lon': '6.48' }, 'id': 'dit:aventri:Event:200200648', 'name': 'You Can Export: Introduction to Export Market Research', 'url': 'https://eu.eventscloud.com/200200648', 'content': 'Marketing research is the first and one of the most vital steps for any organisation considering entering a new market. This intensive half-day course is an invaluable introduction to the process of planning and conducting marketing research overseas.', 'startdate': '2020-03-18', 'enddate': '2020-03-18', 'foldername': 'Northwest', 'location': {'name': 'Mercure Hotel St Helens', 'address1': 'Linkway West', 'address2': '', 'address3': '', 'city': 'St Helens', 'state': 'Merseyside', 'postcode': 'WA10 1NG', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200200783:Create', 'type': 'Search', 'eventid': '200200783', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '30.07', 'lon': '7.83' }, 'id': 'dit:aventri:Event:200200783', 'name': 'Food and drink taster visit to Bruges', 'url': 'https://eu.eventscloud.com/200200783', 'content': 'Join the Department for International Trade (DIT) and Northern Powerhouse Export Champion David Greenwood-Haigh from Coeur de Xocolat on this taster mission to bruges', 'startdate': '2020-03-19', 'enddate': '2020-03-21', 'foldername': 'Yorkshire & Humber', 'location': {'name': '', 'address1': '', 'address2': '', 'address3': '', 'city': 'Bruges', 'state': '', 'postcode': '', 'country': 'Belgium', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200200900:Create', 'type': 'Search', 'eventid': '200200900', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '00.09', 'lon': '9.00' }, 'id': 'dit:aventri:Event:200200900', 'name': 'The GREAT Entrepreneur Games Barcelona 2020', 'url': 'https://eu.eventscloud.com/200200900', 'content': 'Looking to uncover the most outstanding entrepreneurs across Spain, the UK’s Department for International Trade (DIT) will be hosting Barcelona chapter of the GREAT Entrepreneur Games which will take place on\xa0the 25th of March\xa02020.\xa0 The dealine for applications is 15th March\xa02020. Click through to learn more and apply.', 'startdate': '2020-03-25', 'enddate': '2020-03-25', 'foldername': 'Spain', 'location': {'name': 'InGracia Events', 'address1': 'Carrer de Jesús, 3-5 ', 'address2': '', 'address3': '', 'city': 'Barcelona', 'state': '', 'postcode': '08012', 'country': 'Spain', 'phone': '', 'email': '', 'map': 'https://www.google.com/maps/place/INGRACIA+EVENTS+BARCELONA/@41.398388,2.1589884,18z/data=!4m5!3m4!1s0x12a4a297aa4b78e9:0xfcf6f30d38b52b8b!8m2!3d41.3988507!4d2.1573048'}, 'language': 'eng', 'timezone': '[GMT+01:00] Brussels, Copenhagen, Madrid, Paris', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200201219:Create', 'type': 'Search', 'eventid': '200201219', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '90.12', 'lon': '2.19' }, 'id': 'dit:aventri:Event:200201219', 'name': 'Going Global - Digital Tools for International Growth', 'url': 'https://eu.eventscloud.com/200201219', 'content': '<p>Are you looking to grow your business and enhance profit margins? Do you want to hear how online selling could get your B2B business new customers in new markets?\xa0</p>\r\n\r\n<p>‘Going Global – Digital Tools for International Growth’ is a fringe event as part of the inaugural Digital City Festival – five days of events showcasing the best in digital.</p>', 'startdate': '2020-03-09', 'enddate': '2020-03-09', 'foldername': 'Northwest', 'location': {'name': 'The Studio', 'address1': 'The Hive', 'address2': '51 Lever Street', 'address3': '', 'city': 'Manchester', 'state': 'Greater Manchester', 'postcode': 'M1 1FN', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200201351:Create', 'type': 'Search', 'eventid': '200201351', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '10.13', 'lon': '3.51' }, 'id': 'dit:aventri:Event:200201351', 'name': 'Europe Healthcare & Life Sciences Trade Roadshow 2020', 'url': 'https://eu.eventscloud.com/200201351', 'content': "Your chance to meet DIT's commercial officers from around Europe, pitch your product and get advice on how to break into European markets as well as finding out the support on offer. ", 'startdate': '2020-03-16', 'enddate': '2020-03-18', 'foldername': 'Healthcare and Life Science', 'location': {'name': 'Midlands and North of England', 'address1': '', 'address2': '', 'address3': '', 'city': 'Daresbury, Leeds, Loughborough', 'state': '', 'postcode': '', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200201864:Create', 'type': 'Search', 'eventid': '200201864', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '40.18', 'lon': '8.64' }, 'id': 'dit:aventri:Event:200201864', 'name': 'WeChat Masterclass by PingPong Digital', 'url': 'https://eu.eventscloud.com/200201864', 'content': 'Attend a thought-provoking live and interactive demonstration of how to set up a WeChat group, how to use QR Codes and how the Chinese community use the WeChat app.', 'startdate': '2020-03-24', 'enddate': '2020-03-24', 'foldername': 'West Midlands', 'location': {'name': 'Fazeley Studios', 'address1': '191 Fazeley St', 'address2': '', 'address3': '', 'city': 'Birmingham', 'state': '', 'postcode': 'B5 5SE', 'country': '', 'phone': '', 'email': '', 'map': 'https://www.google.com/maps/place/Fazeley+Studios/@52.4777778,-1.8838554,17z/data=!3m1!4b1!4m5!3m4!1s0x4870bc81c7e17e39:0xc5b2379187cf4e05!8m2!3d52.4777778!4d-1.8816667'}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200201885:Create', 'type': 'Search', 'eventid': '200201885', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '50.18', 'lon': '8.85' }, 'id': 'dit:aventri:Event:200201885', 'name': 'You Can Export: Pitching for Business Overseas', 'url': 'https://eu.eventscloud.com/200201885', 'content': "When face-to-face with prospective customers, you'll need to persuade them why they should be buying from you rather than your competitors. In this session, participants will gain an insight into some of the elements that make successful salespeople successful.", 'startdate': '2020-04-22', 'enddate': '2020-04-22', 'foldername': 'Yorkshire & Humber', 'location': {'name': 'A-SAFE Headquarters', 'address1': 'Habergham Works', 'address2': 'Ainley’s Industrial Estate', 'address3': '', 'city': 'Elland', 'state': '', 'postcode': 'HX5 9JP', 'country': 'Country', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200201987:Create', 'type': 'Search', 'eventid': '200201987', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '70.19', 'lon': '9.87' }, 'id': 'dit:aventri:Event:200201987', 'name': 'Establishing Business in Germany', 'url': 'https://eu.eventscloud.com/200201987', 'content': 'For new and existing exporters alike, this seminar is suitable for any UK business looking to establish a presence in Germany. We are bringing experts together, including those that are currently living and working in the market, to share insights that will help you to enter and thrive in Germany.', 'startdate': '2020-04-28', 'enddate': '2020-04-28', 'foldername': 'Yorkshire & Humber', 'location': {'name': 'Advanced Manufacturing Park', 'address1': 'Brunel Way', 'address2': '', 'address3': '', 'city': 'Rotherham', 'state': 'County', 'postcode': 'S60 5WG', 'country': 'Country', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202041:Create', 'type': 'Search', 'eventid': '200202041', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '10.20', 'lon': '0.41' }, 'id': 'dit:aventri:Event:200202041', 'name': 'Business Clinics: Export Opportunities in Indonesia, Thailand and Vietnam', 'url': 'https://eu.eventscloud.com/200202041', 'content': 'The Department for International Trade is running business clinics with the Directors of BritCham from Indonesia and Thailand, and the Director of British Business Group Vietnam to promote ASEAN opportunities for North West businesses.', 'startdate': '2020-03-11', 'enddate': '2020-03-11', 'foldername': 'Northwest', 'location': {'name': 'Lee House', 'address1': '90 Great Bridgewater Street', 'address2': '', 'address3': '', 'city': 'Manchester', 'state': 'Greater Manchester', 'postcode': 'M1 5JW', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202154:Create', 'type': 'Search', 'eventid': '200202154', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '40.21', 'lon': '1.54' }, 'id': 'dit:aventri:Event:200202154', 'name': 'Selling to Africa - A Focus on Life Science Opportunities', 'url': 'https://eu.eventscloud.com/200202154', 'content': 'The largest exports from the East of England to Africa in 2018 were medicinal and pharmaceutical products, with a value of over £90.1 million*. Now is a great time for healthcare and life science companies to be including Africa in their export strategy. \r\n\r\nThe Department for International Trade (DIT) in the East of England is holding a specialised Healthcare and Life Science Africa event focusing on helping SMEs to start or expand their export business to Africa. As well as DIT in-market specialists, we will be joined by Bolaji Sofulu from ETK Group who is excellently placed to give advice on market insight. ', 'startdate': '2020-03-05', 'enddate': '2020-03-05', 'foldername': 'East of England', 'location': {'name': 'The Granta Centre', 'address1': 'Granta Park', 'address2': 'Great Abington', 'address3': '', 'city': 'Cambridge', 'state': '', 'postcode': 'CB21 6AL', 'country': 'United Kingdom', 'phone': '01707 398 398', 'email': 'diteastevents@mobile.trade.gov.uk', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202178:Create', 'type': 'Search', 'eventid': '200202178', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '80.21', 'lon': '1.78' }, 'id': 'dit:aventri:Event:200202178', 'name': 'UK Agritech Mission to New Zealand Fieldays 2020', 'url': 'https://eu.eventscloud.com/200202178', 'content': '<p>The British High Commission Wellington, with our colleagues at the UK Department for International Trade in Auckland, are inviting applications to join a delegation of UK agritech businesses to attend New Zealand\'s <a href="https://www.fieldays.co.nz/">National Agricultural Fieldays 2020</a>.</p>\r\n\r\n<p>\xa0</p>', 'startdate': '2020-06-10', 'enddate': '2020-06-13', 'foldername': 'Australia', 'location': {'name': '', 'address1': '', 'address2': '', 'address3': '', 'city': 'Mystery Creek', 'state': '', 'postcode': '', 'country': 'New Zealand', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT+12:00] Auckland, Wellington', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202193:Create', 'type': 'Search', 'eventid': '200202193', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '30.21', 'lon': '1.93' }, 'id': 'dit:aventri:Event:200202193', 'name': 'Russia Waste Management Roadshow', 'url': 'https://eu.eventscloud.com/200202193', 'content': 'The Department for International Trade is offering businesses an opportunity to meet with key decision makers in the Russian Waste Management sector. This is a great opportunity for North West businesses to present their waste management solutions and showcase their products and services.', 'startdate': '2020-03-13', 'enddate': '2020-03-13', 'foldername': 'Northwest', 'location': {'name': 'University of Salford', 'address1': 'Maxwell Building', 'address2': '43 Crescent Road', 'address3': '', 'city': 'Salford', 'state': 'Greater Manchester', 'postcode': 'M5 4WT', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202198:Create', 'type': 'Search', 'eventid': '200202198', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '80.21', 'lon': '1.98' }, 'id': 'dit:aventri:Event:200202198', 'name': 'YOU CAN EXPORT: Introduction to International Trade   ', 'url': 'https://eu.eventscloud.com/200202198', 'content': '<p style="margin:0cm 0cm 0pt">\xa0</p>\r\n\r\n<p style="margin:0cm 0cm 0pt"><strong>Please note this is a practical event aimed at North East based businesses interested in trading internationally or wanting to learn more about the service Department for International Trade North East (formerly UKTI North East) provides.\xa0</strong></p>', 'startdate': '2020-04-22', 'enddate': '2020-04-22', 'foldername': 'Northeast', 'location': {'name': 'St James Park ', 'address1': 'Strawberry Place ', 'address2': 'Executive Box 645', 'address3': '', 'city': 'Newcastle upon Tyne ', 'state': '', 'postcode': 'NE14ST', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202214:Create', 'type': 'Search', 'eventid': '200202214', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '40.22', 'lon': '2.14' }, 'id': 'dit:aventri:Event:200202214', 'name': 'Registration of Interest: Midlands Engine Life Sciences Market Visit to San Diego, Irvine and Los Angeles', 'url': 'https://eu.eventscloud.com/200202214', 'content': '<p>Register your interest in joining our forthcoming Life Science sector visit to the USA, calling at San Diego, Irvine and LA with the option of visiting the BIO International Convention and Exhibition.</p>', 'startdate': '2020-06-08', 'enddate': '2020-06-12', 'foldername': 'East Midlands', 'location': {'name': 'San Diego, Irvine and Los Angeles', 'address1': '', 'address2': '', 'address3': '', 'city': '', 'state': '', 'postcode': '', 'country': 'USA', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202421:Create', 'type': 'Search', 'eventid': '200202421', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '10.24', 'lon': '4.21' }, 'id': 'dit:aventri:Event:200202421', 'name': 'Welcome Reception for UK Fintech Delegation', 'url': 'https://eu.eventscloud.com/200202421', 'content': '<p><strong><span style="font-size:18px;"><span style="font-family:Arial;">Join us for a welcome reception for our innovative delegation of UK fintech companies.</span></span></strong></p>', 'startdate': '2020-03-16', 'enddate': '2020-03-16', 'foldername': 'Australia', 'location': {'name': 'Investment Centre Victoria', 'address1': 'L46, 55 Collins Street', 'address2': '', 'address3': '', 'city': 'Melbourne', 'state': 'Victoria', 'postcode': '3000', 'country': 'Australia', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT+10:00] Canberra, Melbourne, Sydney', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202445:Create', 'type': 'Search', 'eventid': '200202445', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '50.24', 'lon': '4.45' }, 'id': 'dit:aventri:Event:200202445', 'name': 'Doing Business in Russia', 'url': 'https://eu.eventscloud.com/200202445', 'content': 'The Russian market is growing and there are more opportunities becoming available UK companies to export there. The Department for International Trade invites you to join us in Manchester to hear from experts about the benefits of trading with Russia.', 'startdate': '2020-03-12', 'enddate': '2020-03-12', 'foldername': 'Northwest', 'location': {'name': 'Etihad Stadium', 'address1': 'Ashton New Road', 'address2': '', 'address3': '', 'city': 'Manchester', 'state': 'Greater Manchester', 'postcode': 'M11 3FF', 'country': 'United Kingdom', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202605:Create', 'type': 'Search', 'eventid': '200202605', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '50.26', 'lon': '6.05' }, 'id': 'dit:aventri:Event:200202605', 'name': 'Roundtable Discussion with UK Fintech Delegation', 'url': 'https://eu.eventscloud.com/200202605', 'content': '<p><span style="font-family:Arial;"><span style="font-size:18px;"><strong>Join us for a roundtable discussion with our innovative delegation of UK fintech companies.</strong></span></span></p>', 'startdate': '2020-03-16', 'enddate': '2020-03-16', 'foldername': 'Australia', 'location': {'name': 'Investment Centre Victoria', 'address1': 'L46, 55 Collins Street', 'address2': '', 'address3': '', 'city': 'Melbourne', 'state': 'Victoria', 'postcode': '3000', 'country': 'Australia', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT+10:00] Canberra, Melbourne, Sydney', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202636:Create', 'type': 'Search', 'eventid': '200202636', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '60.26', 'lon': '6.36' }, 'id': 'dit:aventri:Event:200202636', 'name': 'Selling to the USA - A Focus on Med-Tech Opportunities', 'url': 'https://eu.eventscloud.com/200202636', 'content': 'The United States leads the world in the production of medical technologies and is the industry’s largest consumer. With new and innovative technologies coming to market, the medical technologies industry in the USA is highly competitive and well-positioned for future growth.  \r\n\r\nThe Department for International Trade (DIT) in the East of England have created a workshop focusing on specific opportunities available to UK med-tech businesses in Texas and Boston. We will be joined by Autumn Waska, DIT Houston, Trade & Investment Officer and Jeff Dillon the Vice Consul, Healthcare Trade & Investment Officer in Boston. \r\n', 'startdate': '2020-03-31', 'enddate': '2020-03-31', 'foldername': 'East of England', 'location': {'name': 'Madingley Hall ', 'address1': 'Madingley ', 'address2': '', 'address3': '', 'city': 'Cambridge', 'state': '', 'postcode': 'CB23 8AQ', 'country': 'United Kingdom', 'phone': '01707 398 398', 'email': 'diteastevents@mobile.trade.gov.uk', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202875:Create', 'type': 'Search', 'eventid': '200202875', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '50.28', 'lon': '8.75' }, 'id': 'dit:aventri:Event:200202875', 'name': 'Life Sciences and Healthcare: Exporting to Latin America & the Caribbean', 'url': 'https://eu.eventscloud.com/200202875', 'content': '<p>Join us to discuss export opportunities in Latin America & the Caribbean (LATAC) and request 1-2-1 meetings with representatives from Brazil, Mexico, Colombia and the Caribbean.</p>', 'startdate': '2020-03-11', 'enddate': '2020-03-11', 'foldername': 'East Midlands', 'location': {'name': 'Medicity', 'address1': 'D6 Thane Road', 'address2': '', 'address3': '', 'city': 'Nottingham', 'state': '', 'postcode': 'NG90 6BH', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202932:Create', 'type': 'Search', 'eventid': '200202932', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '20.29', 'lon': '9.32' }, 'id': 'dit:aventri:Event:200202932', 'name': 'Doing Business in the USA 1-2-1 meetings ', 'url': 'https://eu.eventscloud.com/200202932', 'content': '<p>The Department for International Trade are hosting four specialists who are\xa0visiting the\xa0Southwest to offer\xa0businesses 1-2-1 meetings on doing business in the USA.</p>', 'startdate': '2020-03-20', 'enddate': '2020-03-20', 'foldername': 'Southwest', 'location': {'name': 'Leigh Court', 'address1': 'Abbots Leigh', 'address2': '', 'address3': '', 'city': 'Bristol', 'state': '', 'postcode': 'BS8 3RA', 'country': 'United Kingdom', 'phone': '', 'email': 'events@businesswest.co.uk', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'}}, 
            {'id': 'dit:aventri:Event:200202985:Create', 'type': 'Search', 'eventid': '200202985', 'dit:application': 'aventri', 'object': {'type': ['Event', 'dit:aventri:Event'], 'geocoordinates': { 'lat': '50.29', 'lon': '9.85' }, 'id': 'dit:aventri:Event:200202985', 'name': 'DIT Masterclass: Researching Export Markets', 'url': 'https://eu.eventscloud.com/200202985', 'content': '<p>This free workshop will give you all the information you need to understand the potential for your company overseas.</p>', 'startdate': '2020-04-07', 'enddate': '2020-04-07', 'foldername': 'East Midlands', 'location': {'name': 'The Export Hub', 'address1': 'Morningside Arena', 'address2': '31 Charter Street', 'address3': '', 'city': 'Leicester', 'state': '', 'postcode': 'LE1 3UD', 'country': '', 'phone': '', 'email': '', 'map': ''}, 'language': 'eng', 'timezone': '[GMT] Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London', 'currency': 'Sterling', 'price_type': None, 'price': None, 'published': '2020-03-05T12:39:18.438792'} }
        ]

        # now = datetime.datetime.now().isoformat()
        # return [
        #     {
        #         'id': 'dit:aventri:Event:' + str(event['eventid']) + ':Create',
        #         'type': 'Search',
        #         'eventid': event['eventid'],
        #         'dit:application': 'aventri',
        #         'object': {
        #             'type': ['Event', 'dit:aventri:Event'],
        #             'id': 'dit:aventri:Event:' + event['eventid'],
        #             'name': event['name'],
        #             'url': event['url'],
        #             'content': event['description'],
        #             'startdate': event['startdate'],
        #             'enddate': event['enddate'],
        #             'foldername': event['foldername'],
        #             'location': event['location'],
        #             'geocoordinates': event['geocoordinates'],
        #             'language': event['defaultlanguage'],
        #             'timezone': event['timezone'],
        #             'currency': event['standardcurrency'],
        #             'price_type': event['price_type'],
        #             'price': event['pricepoints'],
        #             'published': now,
        #         }
        #     }
        #     for page_event in page
        #     for event in [await get_event(page_event['eventid'])]
        #     if self.should_include(context, event)
        # ]

    def should_include(self, context, event):
        # event must be not deleted
        # startdate should be >= today and not null
        # enddate should be >= startdate and not null
        # folderid or foldername should be != internal events folder
        # name, url, description should be not null

        allowed_folders = self.whitelisted_folders.split(',')
        now = datetime.datetime.today().strftime('%Y-%m-%d')
        try:
            should_include = (
                event['eventid'] is not None and
                event['deleted'] != 0 and
                event['enddate'] >= event['startdate'] >= now and
                event['name'] is not None and
                event['url'] is not None and
                event['description'] is not None and
                event['include_calendar'] == '1' and
                event['status'] == 'Live' and
                event['foldername'] in allowed_folders
            )

        except KeyError:
            should_include = False

        loggable_event = {
            key: event[key]
            for key in (
                'eventid', 'deleted', 'enddate', 'startdate', 'name', 'url', 'description',
                'include_calendar', 'status', 'foldername',
            )
            if key in event
        }
        context.logger.debug('Event data: (%s) should_include: (%s)',
                             loggable_event, should_include)

        return should_include
